name: Project Unit tests

on:
  pull_request:
    branches: [ master ]

env:
  code_path: 'src/**'
  test_path: 'test/**'

jobs:
  check_changing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Check does code or test changed
      uses: dorny/paths-filter@v2
      id: changed_obj
      with:
        # inline YAML or path to separate file (e.g.: .github/filters.yaml)
        filters: |
          code:
            - ${{ env.code_path }}
          test:
            - ${{ env.test_path }}
    
    outputs:
      code_changed: ${{ steps.changed_obj.outputs.code }}  
      test_changed: ${{ steps.changed_obj.outputs.test }}  

  testing:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    needs: check_changing
    if: ${{ needs.check_changing.outputs.code_changed == 'true' || needs.check_changing.outputs.test_changed == 'true' }}
    
    services:
      postgres:
        image: postgres:14.3

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build Release
        run: dotnet build --configuration Debug --no-restore
      - name: Run tests in Debug mode
        run: dotnet test --configuration Debug --verbosity m --no-restore
        env: 
          ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres"
      - name: Build Release
        run: dotnet build --configuration Release --no-restore
      - name: Run tests in Release mode
        run: dotnet test --configuration Release --verbosity m --no-restore
        env: 
          ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres"
